### ISSUE TITLE
how to save a video frame instead of the whole canvas ?

### ISSUE THREAD

**Issue by stephanschulz** [cdaein/p5js-electron-canvas-saver-boilerplate#10]
Thanks for making this example.

How would I save frames from a webcam with your code?

I tried something like this which sends an image to the function.
But no luck so far.
```
function sendSnapshotDataToElectron(content) {
    //  const dataURL = content.elt.toDataURL('image/png');

    var imgBlob = new Blob([content], {type: 'image/png'});
    const dataURL = URL.createObjectURL(imgBlob);

    const fileName = (frameCount-startFrame) + '.png';
    const data = { dataURL, fileName };
    ipcRenderer.send('image:save', data);
    console.log(`saving snapshot... ${fileName}`);
}
```
Thanks for any advice.

**Comment by cdaein** [comment]
my project only records what's on the html5 canvas, but not any other html elements. so if you want to record webcam image, you should first draw the image onto the canvas.
