### ISSUE TITLE
Is there a way I can save as .bmp instead of .png?

### ISSUE THREAD

**Issue by Raj123456788** [cdaein/p5js-electron-canvas-saver-boilerplate#4]

**Comment by cdaein** [comment]
I am not sure, but I suggest you take a look at this repo as that's what I used for exporting media files:
https://github.com/fluent-ffmpeg/node-fluent-ffmpeg

**Comment by Raj123456788** [comment]
Thanks for the link.  The images created are of width & height 794 X 551px. Do you know how can I set it 1280 X 720 instead? I am trying to get this working for long time.
